---
application:
  name: "garbgae"
  project: "market2"
  organization: "QoveryCommunity"
  storage:
  - name: "dockopus"
    size: "10"
    type: "ssd"
    mount_point: "/mnt/dockopus"
databases:
- type: "MYSQL"
  name: "freddy"
  version: "5.6"
routers:
- name: "main-garbgae"
  routes:
  - application_name: "garbgae"
    paths:
    - "/*"
